Repository skynet-guide/docs, pull requests merged in 2021-05, with the labels that each got.

#35 minor grammar tweaks
  docs/discover/resource-sites/index.en.md
Labels: grammar

#36 spelling/few grammar mistakes
  docs/discover/skynet-apps/index.en.md
Labels: grammar

#42 lithuanian translation #1
  docs/discover/block-chain-explorers/index.lt.md
  docs/discover/built-with-sia/index.lt.md
  docs/discover/foundation-tracker/index.lt.md
  docs/discover/network-metrics/index.lt.md
  docs/index.lt.md
  mkdocs.yml
  requirements.txt
Labels: translation

#46 create host guide
  docs/hosting/setup-linux-server/index.en.md
  docs/static/assets/hosting/hosting-with-siad/sia-tech-website.png
Labels: new article

#48 Update repo readme
  README.md
Labels: documentation
