Repository skynet-guide/docs, pull requests merged in 2021-04, with the labels that each got.

#18 this should work for the build process, made a small change to find o…
  .github/workflows/deploy.yml
  docs/index.md
Labels: safe to build

#19 changed data key to something relevant
  .github/workflows/deploy.yml
Labels: safe to build

#20 fixed path issues
  .github/workflows/deploy.yml
  docs/pages/help/faq/en.md
  docs/pages/rent/renting-on-sia/en.md
  docs/pages/skynet-for-users/sending-files-over-skynet/en.md
Labels: safe to build

#23 update articles
  docs/discover/block-chain-explorers/index.en.md
  docs/discover/built-with-sia/index.en.md
  docs/discover/foundation-tracker/index.en.md
  docs/discover/network-metrics/index.en.md
  docs/discover/resource-sites/index.en.md
  docs/discover/skynet-apps/index.en.md
  docs/discover/storage-chains-compared/index.en.md
  docs/discover/tools/index.en.md
  docs/help/contact-support/index.en.md
  docs/help/contributors/index.en.md
  docs/help/faq/index.en.md
  docs/hosting/index.en.md
  docs/rent/before-you-start/index.en.md
  docs/rent/renting-on-sia/index.en.md
  docs/sia/foundation/index.en.md
  docs/sia/history/index.en.md
  docs/sia/introduction/index.en.md
  docs/sia/mining-guide/index.en.md
  docs/sia/renting/index.en.md
  docs/sia/seed-management/index.en.md
  docs/sia/tokenomics/index.en.md
  docs/sia/trading/index.en.md
  docs/sia/wallet/index.en.md
  docs/skynet-for-users/sending-files-over-skynet/index.en.md
  docs/skynet-for-users/why-do-i-need-skynet/index.en.md
  docs/skynet/introduction/index.en.md
  docs/skynet/portals/index.en.md
Labels: safe to build

#26 Danger edits
  docs/discover/block-chain-explorers/index.en.md
  docs/help/contributors/index.en.md
  docs/help/faq/index.en.md
  docs/hosting/index.de.md
  docs/index.de.md
  docs/index.md
  docs/sia/introduction/index.en.md
  docs/sia/mining-guide/index.en.md
  docs/skynet-for-users/sending-files-over-skynet/index.en.md
  docs/skynet/portals/index.en.md
  docs/static/assets/favicon.png
Labels: safe to build

#27 espanol home page added(from gumil)
  docs/help/contributors/index.en.md
  docs/index.de.md
  docs/index.es.md
  mkdocs.yml
Labels: translation

#28 Add edit page button
  mkdocs.yml
Labels: enhancement

#29 Change build workflow on PR
  .github/workflows/build_pr.yml
Labels: enhancement
